Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: alumnus-auth-pool
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: user_id
          Mutable: false
          AttributeDataType: String
        - Name: name
          Mutable: true
          AttributeDataType: String
      Policies:
        PasswordPolicy:
          MinimumLength: 6
      AutoVerifiedAttributes: ["email"]

  UserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: user-pool-ui
      GenerateSecret: false
      UserPoolId: { Ref: UserPool }
      AccessTokenValidity: 5
      IdTokenValidity: 5
      ExplicitAuthFlows:
        - "ADMIN_NO_SRP_AUTH"
